# Generated by Django 4.0.3 on 2022-04-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
