# Generated by Django 4.0.3 on 2022-04-27 18:56

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_admin_password_remove_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
