# Generated by Django 4.0.4 on 2022-04-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_fullname_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(default='images/image1.jpg', upload_to='images/'),
        ),
    ]
