# Generated by Django 4.0.4 on 2022-04-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transport_booking'),
        ('main', '0008_alter_storage_image'),
    ]

    operations = [
    ]
