# Generated by Django 4.0.4 on 2022-04-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_0003_transport_booking_0008_alter_storage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='kurgatfelo@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='felo', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
    ]
