# Generated by Django 3.2 on 2022-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_located_transport_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='exit_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
