# Generated by Django 3.2 on 2022-05-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220502_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transport',
        ),
    ]
