# Generated by Django 3.2 on 2022-05-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220502_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainstorage', to='main.storage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintransport', to='main.transport'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
